rack:
  url: https://github.com/rack/rack.git
  command: bundle exec rake test
falcon:
  url: https://github.com/socketry/falcon.git
  command: bundle exec bake test
puma:
  url: https://github.com/puma/puma.git
  command: bundle exec rake test
